[tool.poetry]
name = "cloudwatch"
version = "0.1.0"
description = ""
authors = ["Krzysztof Olszewski <hello@deltacode.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.26.64"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
